import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--background)",
        foreground: "var(--foreground)",
        // Codex 调色盘 (精准对齐官方截图采样)
        canvas: "#181818",
        sidebar: "#262628",
        "surface-sidebar": "#38393B",
        surface: "#242424",
        "surface-hover": "#2F2F32",
        composer: "#2A2A2A",
        "composer-border": "#383838",
        hairline: "#303033",
        "hairline-hover": "#404044",
        // 兼容原引用并扩展
        void: "#181818",
        elevated: "#242424",
        accent: {
          blue: "#2563EB",
          cyan: "#22D3EE",
          purple: "#A855F7",
          green: "#10B981",
          orange: "#F97316",
          amber: "#F59E0B",
          emerald: "#10B981",
          coral: "#F43F5E",
        },
        codex: {
          text: "#ECECEE",
          muted: "#8E8E93",
          subtle: "#636366",
        },
        genesis: {
          primary: "#ECECEE",
          secondary: "#8E8E93",
          muted: "#636366",
          code: "#E5E7EB",
        },
      },
      fontFamily: {
        sans: [
          '"Plus Jakarta Sans"',
          "-apple-system",
          "BlinkMacSystemFont",
          '"PingFang SC"',
          '"Hiragino Sans GB"',
          '"Microsoft YaHei"',
          '"Segoe UI"',
          "Roboto",
          "sans-serif",
        ],
        serif: [
          '"Newsreader"',
          "Georgia",
          "Cambria",
          '"Times New Roman"',
          "-apple-system",
          "BlinkMacSystemFont",
          '"PingFang SC"',
          '"Hiragino Sans GB"',
          '"Microsoft YaHei"',
          "sans-serif",
        ],
        "claude-serif": [
          '"Newsreader"',
          "Georgia",
          "Cambria",
          '"Times New Roman"',
          "-apple-system",
          "BlinkMacSystemFont",
          '"PingFang SC"',
          '"Hiragino Sans GB"',
          '"Microsoft YaHei"',
          "sans-serif",
        ],
        mono: [
          '"JetBrains Mono"',
          "ui-monospace",
          "SFMono-Regular",
          "Menlo",
          "Monaco",
          "Consolas",
          '"Liberation Mono"',
          '"Courier New"',
          "monospace",
        ],
      },
      borderWidth: {
        hairline: "1px",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};
export default config;
